CREATE DATABASE RACING
GO
USE RACING
GO

CREATE TABLE SECTORES
(
ID INT IDENTITY (1,1),
SECTOR VARCHAR(100),
PRECIO MONEY

CONSTRAINT PK_SECTORES PRIMARY KEY (ID)
);
GO

CREATE TABLE DETALLE_ENTRADA
(
ID INT IDENTITY (1,1),
SECTOR INT,
BUTACA INT,
PRECIO MONEY

CONSTRAINT PK_DETALLE_ENTRADA PRIMARY KEY (ID)

CONSTRAINT FK_DETALLE_ENTRADA_SECTORES FOREIGN KEY (SECTOR)
REFERENCES SECTORES (ID)
);
GO


INSERT INTO SECTORES (SECTOR, PRECIO) VALUES 
('Platea Alta Centro',195000),
('Platea Alta Extremos',162000),
('Platea Baja',300400),
('Platea Baja Central',381300),
('Platea Media Central',381300),
('Platea Media Extremos',300400),
('Plateas Preferenciales',782000),
('Palcos Primer Piso',557700),
('Palcos Segundo Piso',433700),
('Palcos Tercer Piso',395800),
('Torres - Terraza',410000);
GO

CREATE PROCEDURE SP_POST_ENTRADA
@SECTOR INT,
@BUTACA INT,
@PRECIO MONEY,
@ID INT OUTPUT
AS
BEGIN
	INSERT INTO DETALLE_ENTRADA (SECTOR,BUTACA,PRECIO)
	VALUES (@SECTOR,@BUTACA,@PRECIO);

	SET @ID = SCOPE_IDENTITY();
END;